-- Schema for the PostgreSQL currency_exchange database.

CREATE TABLE currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    code VARCHAR(3) NOT NULL UNIQUE,
    sign VARCHAR(1) NOT NULL
);

CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency_id BIGINT NOT NULL REFERENCES currencies(id),
    target_currency_id BIGINT NOT NULL REFERENCES currencies(id),
    rate NUMERIC(12, 6) NOT NULL CHECK (rate > 0),
    CONSTRAINT exchange_rates_currency_pair_unique
        UNIQUE (base_currency_id, target_currency_id),
    CONSTRAINT exchange_rates_different_currencies
        CHECK (base_currency_id <> target_currency_id)
);
